(function () {
    const bootstrap = window.PLAYER_BOOTSTRAP || {};
    const PAD_AFTER_SPEECH = 0.8;
    const $ = id => document.getElementById(id);
    const qs = p => new URLSearchParams(location.search).get(p);

    const PROJECT_BASE = normalizeBase(bootstrap.projectBase || '');
    // Trust boundary: flow locations come only from the host page. Public project data and
    // query parameters are untrusted; Electron/editor previews use flowData, and portable
    // players embed flowData, so none of those trusted modes need a ?src= escape hatch.
    const FLOW_URL = bootstrap.flowUrl || '';
    const FLOW_DATA = bootstrap.flowData || null;
    const IMG_ASSETS = normalizeBase(bootstrap.imgBase || (PROJECT_BASE ? PROJECT_BASE + 'img/' : 'img/'));
    const SPEECH_ASSETS = normalizeBase(bootstrap.speechBase || (PROJECT_BASE ? PROJECT_BASE + 'speech/' : 'speech/'));
    const AUDIO_ASSETS = normalizeBase(bootstrap.audioBase || (PROJECT_BASE ? PROJECT_BASE + 'audio/' : 'audio/'));
    const ENGINE_BASE = normalizeBase(bootstrap.engineBase || '/effects/');
    const TRANSITION_ENGINE_BASE = normalizeBase(bootstrap.transitionEngineBase || '/transitions/');
    // Inline registries are trusted host code generated by the portable exporters. They are
    // deliberately distinct from engine names and paths found inside untrusted flow data.
    const HAS_INLINE_ENGINES = Object.prototype.hasOwnProperty.call(bootstrap, 'inlineEngines');
    const HAS_INLINE_TRANSITIONS = Object.prototype.hasOwnProperty.call(bootstrap, 'inlineTransitions');
    const INLINE_ENGINES = bootstrap.inlineEngines && typeof bootstrap.inlineEngines === 'object'
        ? bootstrap.inlineEngines
        : {};
    const INLINE_TRANSITIONS = bootstrap.inlineTransitions && typeof bootstrap.inlineTransitions === 'object'
        ? bootstrap.inlineTransitions
        : {};
    const TRANSITION_ENGINE_VERSION = String(bootstrap.transitionEngineVersion || Date.now());
    const CACHE_BUST_SPEECH = !!bootstrap.cacheBustSpeech;
    // Number of upcoming slides kept ready. Change this bootstrap value to tune the window.
    const PRELOAD_AHEAD_SLIDES = Math.max(0, Math.floor(Number(bootstrap.preloadAheadSlides ?? 4) || 0));
    const SESSION_MEDIA_VERSION = String(Date.now());
    const IS_EDITOR_PREVIEW = qs('preview') === 'editor';

    function normalizeBase(base) {
        if (!base) return '';
        return base.endsWith('/') ? base : base + '/';
    }

    function safeModuleSlug(raw) {
        if (typeof raw !== 'string') return '';
        const slug = raw.trim();
        return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug) ? slug : '';
    }

    function effectEngineSlug(definition) {
        return definition && typeof definition === 'object'
            ? safeModuleSlug(definition.engine)
            : '';
    }

    function registeredModuleSlugs(registryData) {
        const slugs = new Set();
        if (!Array.isArray(registryData)) return slugs;
        registryData.forEach(group => {
            String(group && group.engines || '').split(',').forEach(raw => {
                const slug = safeModuleSlug(raw);
                if (slug) slugs.add(slug);
            });
        });
        return slugs;
    }

    function trustedInlineModuleSlugs(inlineRegistry) {
        return new Set(Object.keys(inlineRegistry || {}).map(safeModuleSlug).filter(Boolean));
    }

    function moduleEnginePath(base, slug) {
        const safeSlug = safeModuleSlug(slug);
        return safeSlug ? normalizeBase(base) + safeSlug + '-engine.js' : '';
    }

    async function loadApprovedModuleSlugs(base, inlineRegistry, hasInlineRegistry, registryLabel) {
        if (hasInlineRegistry) return trustedInlineModuleSlugs(inlineRegistry);
        const response = await fetch(normalizeBase(base) + 'registry.json', { cache: 'no-store' });
        if (!response.ok) throw new Error(`Could not load the approved ${registryLabel} registry`);
        return registeredModuleSlugs(await response.json());
    }

    let approvedEffectSlugsPromise = null;
    let approvedTransitionSlugsPromise = null;

    function approvedEffectSlugs() {
        if (!approvedEffectSlugsPromise) {
            approvedEffectSlugsPromise = loadApprovedModuleSlugs(
                ENGINE_BASE,
                INLINE_ENGINES,
                HAS_INLINE_ENGINES,
                'effect'
            );
        }
        return approvedEffectSlugsPromise;
    }

    function approvedTransitionSlugs() {
        if (!approvedTransitionSlugsPromise) {
            approvedTransitionSlugsPromise = loadApprovedModuleSlugs(
                TRANSITION_ENGINE_BASE,
                INLINE_TRANSITIONS,
                HAS_INLINE_TRANSITIONS,
                'transition'
            );
        }
        return approvedTransitionSlugsPromise;
    }

    // This early exit is available only to the regression test's trusted bootstrap. Keeping
    // the policy hooks here lets tests execute the real validation without initializing a DOM.
    if (bootstrap.securityPolicyTestMode === true) {
        window.__PLAYER_SECURITY_POLICY__ = Object.freeze({
            flowUrl: FLOW_URL,
            safeModuleSlug,
            effectEngineSlug,
            registeredModuleSlugs,
            trustedInlineModuleSlugs,
            moduleEnginePath,
            loadApprovedModuleSlugs
        });
        return;
    }

    function maxPaneHeightPx() {
        return Math.floor(window.innerHeight * 0.85);
    }

    function fitPaneToImage(imgEl) {
        if (!imgEl || imgEl.classList.contains('layer-fg')) return;
        const pane = $('visual');
        if (!imgEl.naturalWidth || !imgEl.naturalHeight || !pane) return;
        const paneWidth = pane.clientWidth || pane.offsetWidth || 0;
        if (!paneWidth) return;
        const target = Math.min(Math.round(paneWidth * (imgEl.naturalHeight / imgEl.naturalWidth)), maxPaneHeightPx());
        pane.style.height = target + 'px';
    }

    function fitPaneToCanvas(canvasEl) {
        if (!canvasEl || canvasEl.classList.contains('layer-fg')) return;
        const pane = $('visual');
        if (!canvasEl.width || !canvasEl.height || !pane) return;
        const paneWidth = pane.clientWidth || pane.offsetWidth || 0;
        if (!paneWidth) return;
        pane.style.height = Math.round(paneWidth * (canvasEl.height / canvasEl.width)) + 'px';
    }

    function sanitizeHTML(input) {
        if (!input) return '';
        const allowed = new Set(['A', 'BR', 'STRONG', 'EM', 'B', 'I', 'P', 'UL', 'OL', 'LI', 'SPAN']);
        const tmp = document.createElement('div');
        tmp.innerHTML = input;
        const elements = [...tmp.querySelectorAll('*')];
        elements.forEach(el => {
            if (!allowed.has(el.tagName)) {
                el.replaceWith(...el.childNodes);
                return;
            }

            [...el.attributes].forEach(attribute => {
                const isSafeLink = el.tagName === 'A'
                    && attribute.name.toLowerCase() === 'href'
                    && /^https?:\/\//i.test(attribute.value);
                if (!isSafeLink) el.removeAttribute(attribute.name);
            });
            if (el.tagName === 'A' && el.hasAttribute('href')) {
                el.setAttribute('rel', 'noopener noreferrer');
                el.setAttribute('target', '_blank');
            }
        });
        return tmp.innerHTML;
    }

    function isAbsoluteAssetPath(v) {
        return /^[a-z][a-z0-9+.-]*:/i.test(v) || v.startsWith('/') || v.startsWith('//');
    }

    function mediaAssetType(v) {
        const val = String(v || '').trim();
        if (/^data:image\//i.test(val)) return 'image';
        if (/^data:audio\//i.test(val)) return 'audio';
        let pathOnly = val.split(/[?#]/, 1)[0];
        // Hosted project media puts the filename in ?p=, not the URL pathname.
        if (/(^|\/)media\.php$/i.test(pathOnly) && val.includes('?')) {
            const query = val.slice(val.indexOf('?') + 1).split('#', 1)[0];
            pathOnly = new URLSearchParams(query).get('p') || '';
        }
        if (/\.(png|jpe?g|webp|gif|avif|bmp|svg)$/i.test(pathOnly)) return 'image';
        if (/\.(mp3|wav|ogg|m4a|aac|flac)$/i.test(pathOnly)) return 'audio';
        return '';
    }

    function resolveAssetPath(v) {
        const val = String(v || '').trim();
        if (!val || isAbsoluteAssetPath(val)) return val;
        if (val.startsWith('img/')) return IMG_ASSETS + val.slice(4);
        if (val.startsWith('speech/')) return SPEECH_ASSETS + val.slice(7);
        if (val.startsWith('audio/')) return AUDIO_ASSETS + val.slice(6);
        if (PROJECT_BASE && val.includes('/')) return PROJECT_BASE + val.replace(/^\/+/, '');
        const assetType = mediaAssetType(val);
        if (assetType === 'image') return IMG_ASSETS + val;
        if (assetType === 'audio') return SPEECH_ASSETS + val;
        return val.replace(/^\.\/+/, '');
    }

    function addSessionMediaVersion(url) {
        if (!CACHE_BUST_SPEECH || !url || url.startsWith('data:') || url.startsWith('blob:')) return url;
        const hashAt = url.indexOf('#');
        const base = hashAt >= 0 ? url.slice(0, hashAt) : url;
        const hash = hashAt >= 0 ? url.slice(hashAt) : '';
        return `${base}${base.includes('?') ? '&' : '?'}v=${encodeURIComponent(SESSION_MEDIA_VERSION)}${hash}`;
    }

    function normalizeEffectConfigAssets(input) {
        if (Array.isArray(input)) return input.map(normalizeEffectConfigAssets);
        if (input && typeof input === 'object') {
            const out = {};
            Object.entries(input).forEach(([k, v]) => {
                out[k] = normalizeEffectConfigAssets(v);
            });
            return out;
        }
        if (typeof input === 'string' && mediaAssetType(input)) {
            return resolveAssetPath(input);
        }
        return input;
    }

    const state = { data: null, slides: [], i: 0, playing: false, userInteracted: false, usingA: true };
    const el = {
        title: $('title'),
        player: $('player'),
        visual: $('visual'),
        introScreen: $('introScreen'),
        startBtn: $('startBtn'),
        opener: $('opener'),
        layerA: $('layerA'),
        layerB: $('layerB'),
        text: $('captionText'),
        captions: $('captionsOverlay'),
        ccBtn: $('ccBtn'),
        controlsBar: $('controlsBar'),
        speech: $('speech'),
        playPause: $('playPauseBtn'),
        prev: $('prevBtn'),
        next: $('nextBtn'),
        back: $('backBtn'),
        exitFullscreen: $('exitFullscreenBtn'),
        fullscreen: $('fullscreenBtn'),
        scrub: $('scrub'),
        posLabel: $('posLabel'),
        maxLabel: $('maxLabel'),
        status: $('status')
    };

    const audioPreloadCache = new Map();
    const audioPreloadPromises = new Map();
    const effectAssetCache = new Map();
    const effectDefCache = new Map();
    const imageCache = new Map();
    const imagePreloadPromises = new Map();
    const effectRegistry = new Map();
    const transitionRegistry = new Map();
    const preloadCache = new Map();
    let nextTimer = null;
    let activeAdvancedTransitionFinish = null;
    let advancedTransitionRequestId = 0;
    let activeAudioElements = [];
    let activeGlobalAudioElements = new Map();

    async function waitForImageDecode(img) {
        if (!img || !img.complete || !img.naturalWidth) return;
        if (typeof img.decode !== 'function') return;
        try { await img.decode(); } catch (e) {}
    }

    function waitForImageElement(img) {
        if (!img) return Promise.resolve();
        if (img.complete) return waitForImageDecode(img);
        return new Promise(resolve => {
            let settled = false;
            const done = async () => {
                if (settled) return;
                settled = true;
                await waitForImageDecode(img);
                resolve();
            };
            img.addEventListener('load', done, { once: true });
            img.addEventListener('error', done, { once: true });
        });
    }

    function waitForVisualPaint() {
        return new Promise(resolve => {
            let settled = false;
            const timeout = setTimeout(done, 120);
            function done() {
                if (settled) return;
                settled = true;
                clearTimeout(timeout);
                resolve();
            }
            requestAnimationFrame(() => requestAnimationFrame(done));
        });
    }

    function waitForEffectReady(readyPromise, timeoutMs = 5000) {
        return new Promise(resolve => {
            let settled = false;
            const timeout = setTimeout(done, timeoutMs);
            function done() {
                if (settled) return;
                settled = true;
                clearTimeout(timeout);
                resolve();
            }
            Promise.resolve(readyPromise).then(done, done);
        });
    }

    function observeCanvasFirstPaint(ctx, onPaint) {
        if (!ctx || typeof onPaint !== 'function') return () => {};
        const methodNames = [
            'drawImage', 'fillRect', 'strokeRect', 'fill', 'stroke',
            'putImageData', 'fillText', 'strokeText'
        ];
        const originals = [];
        let active = true;

        function restore() {
            if (!active) return;
            active = false;
            originals.forEach(({ name, original, hadOwn }) => {
                try {
                    if (hadOwn) ctx[name] = original;
                    else delete ctx[name];
                } catch (e) {}
            });
        }

        methodNames.forEach(name => {
            const original = ctx[name];
            if (typeof original !== 'function') return;
            const hadOwn = Object.prototype.hasOwnProperty.call(ctx, name);
            try {
                ctx[name] = function (...args) {
                    const result = original.apply(ctx, args);
                    if (active) {
                        restore();
                        onPaint();
                    }
                    return result;
                };
                originals.push({ name, original, hadOwn });
            } catch (e) {}
        });

        return restore;
    }

    function loadImagePromise(url) {
        if (!url) return Promise.resolve();
        if (imagePreloadPromises.has(url)) return imagePreloadPromises.get(url);

        let img = imageCache.get(url);
        if (img && img.complete) return waitForImageDecode(img);
        if (!img) {
            img = new Image();
            img.decoding = 'async';
            img.loading = 'eager';
            imageCache.set(url, img);
        }

        const promise = new Promise(resolve => {
            let settled = false;
            const done = async () => {
                if (settled) return;
                settled = true;
                await waitForImageDecode(img);
                resolve();
            };
            img.addEventListener('load', done, { once: true });
            img.addEventListener('error', done, { once: true });
            if (!img.src) img.src = url;
        });
        imagePreloadPromises.set(url, promise);
        return promise;
    }

    function loadAudioPromise(url) {
        if (!url) return Promise.resolve();
        if (audioPreloadPromises.has(url)) return audioPreloadPromises.get(url);

        const promise = new Promise(resolve => {
            const audio = new Audio();
            audio.preload = 'auto';
            let settled = false;
            let timeout = null;
            const done = () => {
                if (settled) return;
                settled = true;
                clearTimeout(timeout);
                resolve();
            };
            timeout = setTimeout(done, 15000);
            audio.addEventListener('canplaythrough', done, { once: true });
            audio.addEventListener('loadeddata', done, { once: true });
            audio.addEventListener('error', done, { once: true });
            audio.src = url;
            audioPreloadCache.set(url, audio);
            try { audio.load(); } catch (e) { done(); }
        });
        audioPreloadPromises.set(url, promise);
        return promise;
    }

    function resolveEffectSpec(spec) {
        if (spec == null) return null;
        if (typeof spec === 'string') {
            const text = spec.trim();
            if (!text) return null;
            if (text.startsWith('{') || text.startsWith('[')) {
                try { return JSON.parse(text); } catch (e) { return text; }
            }
            return text;
        }
        if (typeof spec === 'object') return spec;
        return null;
    }

    function effectSpecKey(spec) {
        const resolved = resolveEffectSpec(spec);
        if (resolved == null) return '';
        if (typeof resolved === 'string') return `name:${resolved}`;
        try { return `obj:${JSON.stringify(resolved)}`; } catch (e) { return `obj:${String(resolved)}`; }
    }

    function collectEffectAssetUrls(obj, bucket = { images: new Set(), audio: new Set() }) {
        if (obj == null) return bucket;
        if (Array.isArray(obj)) {
            obj.forEach(v => collectEffectAssetUrls(v, bucket));
            return bucket;
        }
        if (typeof obj === 'object') {
            Object.values(obj).forEach(v => collectEffectAssetUrls(v, bucket));
            return bucket;
        }
        if (typeof obj !== 'string') return bucket;
        const val = obj.trim();
        if (!val) return bucket;
        const assetType = mediaAssetType(val);
        if (assetType === 'audio') bucket.audio.add(resolveAssetPath(val));
        else if (assetType === 'image') bucket.images.add(resolveAssetPath(val));
        return bucket;
    }

    async function getEffectDefinition(spec) {
        const resolved = resolveEffectSpec(spec);
        if (!resolved) return null;
        const key = effectSpecKey(resolved);
        if (effectDefCache.has(key)) return effectDefCache.get(key);
        const normalized = typeof resolved === 'object'
            ? { ...resolved, config: normalizeEffectConfigAssets(resolved.config || {}) }
            : { engine: resolved, config: {} };
        effectDefCache.set(key, normalized);
        return normalized;
    }

    async function getEffectAssets(spec) {
        const key = effectSpecKey(spec);
        if (!key) return { images: [], audio: [] };
        if (effectAssetCache.has(key)) return effectAssetCache.get(key);
        try {
            const def = await getEffectDefinition(spec);
            const bucket = collectEffectAssetUrls(def ? def.config : {});
            const assets = { images: [...bucket.images], audio: [...bucket.audio] };
            effectAssetCache.set(key, assets);
            return assets;
        } catch (e) {
            const empty = { images: [], audio: [] };
            effectAssetCache.set(key, empty);
            return empty;
        }
    }

    async function getImage(url) {
        if (!url) return null;
        await loadImagePromise(url);
        const cached = imageCache.get(url);
        if (!cached || !cached.naturalWidth) return null;

        // A cached Image is a DOM node. Never append that shared node directly:
        // doing so would move it out of the outgoing slide when a URL is reused.
        const image = cached.cloneNode(false);
        image.decoding = 'sync';
        image.loading = 'eager';
        await waitForImageElement(image);
        return image.naturalWidth ? image : null;
    }

    async function prepareDecodedEffectImages(spec) {
        const assets = await getEffectAssets(spec);
        const entries = await Promise.all(assets.images.map(async url => [url, await getImage(url)]));
        return new Map(entries.filter(([, image]) => image));
    }

    async function loadEffectModule(spec) {
        const def = await getEffectDefinition(spec);
        if (!def) return null;
        const engineName = effectEngineSlug(def);
        if (!engineName) {
            console.error('Invalid or missing effect engine slug');
            return null;
        }
        let approved;
        try {
            approved = await approvedEffectSlugs();
        } catch (e) {
            console.error('Could not verify the approved effect registry', e);
            return null;
        }
        if (!approved.has(engineName)) {
            console.error(`Unregistered effect engine: ${engineName}`);
            return null;
        }
        if (Object.prototype.hasOwnProperty.call(INLINE_ENGINES, engineName)) {
            return { module: INLINE_ENGINES[engineName], config: def.config || {} };
        }

        const enginePath = moduleEnginePath(ENGINE_BASE, engineName);

        let module = effectRegistry.get(enginePath);
        if (!module) {
            try {
                module = await import(enginePath);
                effectRegistry.set(enginePath, module);
            } catch (e) {
                console.error(`Could not load engine: ${enginePath}`, e);
                return null;
            }
        }
        return { module, config: def.config || {} };
    }

    function normalizeTransitionConfig(slide) {
        const draft = slide?.transitionDraft;
        if (!draft || typeof draft !== 'object' || !draft.enabled) return null;
        const engine = safeModuleSlug(draft.engine || 'soft-wipe');
        if (!engine) return null;
        const nestedConfig = draft.config && typeof draft.config === 'object' ? draft.config : {};
        const config = {
            direction: draft.direction,
            duration: draft.duration,
            easing: draft.easing,
            intensity: draft.intensity,
            ...nestedConfig
        };
        return {
            version: Number(draft.version || 1),
            name: draft.name || '',
            engine,
            maker: draft.maker || '',
            config: normalizeEffectConfigAssets(config)
        };
    }

    async function loadTransitionModule(engineName) {
        const engine = safeModuleSlug(engineName);
        if (!engine) return null;
        const approved = await approvedTransitionSlugs();
        if (!approved.has(engine)) {
            throw new Error(`Unregistered transition engine: ${engine}`);
        }
        if (Object.prototype.hasOwnProperty.call(INLINE_TRANSITIONS, engine)) {
            return INLINE_TRANSITIONS[engine];
        }
        const basePath = moduleEnginePath(TRANSITION_ENGINE_BASE, engine);
        const enginePath = basePath + (basePath.includes('?') ? '&' : '?') + 'v=' + encodeURIComponent(TRANSITION_ENGINE_VERSION);
        let module = transitionRegistry.get(enginePath);
        if (!module) {
            module = await import(enginePath);
            transitionRegistry.set(enginePath, module);
        }
        return module;
    }

    async function setVisual(slide, layerEl, effectRuntimeConfig = {}) {
        const bg = slide.background || {};
        const foregroundLayers = (slide.foregroundLayers || []).filter(Boolean);
        let preparedBackgroundImage = null;
        let preparedBackgroundEffectImages = new Map();
        let loadedBackgroundEffect = null;
        let mountedEffect = false;
        let backgroundEffectReady = null;
        const foregroundEffectReadiness = [];

        if (bg.effect) {
            await preloadEffectAssets(bg.effect);
            preparedBackgroundEffectImages = await prepareDecodedEffectImages(bg.effect);
            if (bg.src && !preparedBackgroundEffectImages.has(bg.src)) {
                const backgroundSource = await getImage(bg.src);
                if (backgroundSource) preparedBackgroundEffectImages.set(bg.src, backgroundSource);
            }
            loadedBackgroundEffect = await loadEffectModule(bg.effect);
        } else if (bg.src) {
            preparedBackgroundImage = await getImage(bg.src);
        }

        const preparedForegroundLayers = await Promise.all(foregroundLayers.map(async layer => {
            if (!layer.effect) {
                return { layer, image: await getImage(layer.src), loadedEffect: null };
            }
            await preloadEffectAssets(layer.effect);
            const preloadedImages = await prepareDecodedEffectImages(layer.effect);
            if (layer.src && !preloadedImages.has(layer.src)) {
                const layerSource = await getImage(layer.src);
                if (layerSource) preloadedImages.set(layer.src, layerSource);
            }
            return {
                layer,
                image: null,
                loadedEffect: await loadEffectModule(layer.effect),
                preloadedImages
            };
        }));

        if (Array.isArray(layerEl._cleanupEffects)) {
            layerEl._cleanupEffects.forEach(cleanup => {
                try { cleanup(); } catch (e) {}
            });
            layerEl._cleanupEffects = [];
        } else if (layerEl._cleanupEffect) {
            layerEl._cleanupEffect();
            layerEl._cleanupEffect = null;
        }
        layerEl.innerHTML = '';

        if (bg.effect) {
            const canvas = document.createElement('canvas');
            canvas.className = 'layer-bg';
            layerEl.appendChild(canvas);
            const loadedBg = loadedBackgroundEffect;
            if (loadedBg && loadedBg.module && loadedBg.module.mount) {
                const context = canvas.getContext('2d');
                let signalFirstPaint;
                backgroundEffectReady = new Promise(resolve => { signalFirstPaint = resolve; });
                const stopPaintObserver = observeCanvasFirstPaint(context, signalFirstPaint);
                let cleanup;
                try {
                    cleanup = loadedBg.module.mount(canvas, context, {
                        ...loadedBg.config,
                        ...effectRuntimeConfig,
                        preloadedImages: preparedBackgroundEffectImages,
                        layerPlacement: 'background',
                        onResize: fitPaneToCanvas
                    });
                } catch (error) {
                    stopPaintObserver();
                    throw error;
                }
                const cleanupWithObserver = () => {
                    stopPaintObserver();
                    if (typeof cleanup === 'function') cleanup();
                };
                layerEl._cleanupEffects = [...(layerEl._cleanupEffects || []), cleanupWithObserver];
                mountedEffect = true;
            }
        } else if (preparedBackgroundImage) {
            const imgBg = preparedBackgroundImage;
            if (imgBg) {
                imgBg.className = 'layer-bg';
                const onReady = () => fitPaneToImage(imgBg);
                if (!imgBg.complete || !imgBg.naturalWidth) imgBg.addEventListener('load', onReady, { once: true });
                else onReady();
                layerEl.appendChild(imgBg);
            }
        }

        for (const prepared of preparedForegroundLayers) {
            const { layer } = prepared;
            if (!layer.effect) {
                const imgFg = prepared.image;
                if (!imgFg) continue;
                imgFg.className = 'layer-fg';
                layerEl.appendChild(imgFg);
                continue;
            }

            const loadedFg = prepared.loadedEffect;
            if (!loadedFg || !loadedFg.module || !loadedFg.module.mount) {
                continue;
            }

            const canvas = document.createElement('canvas');
            canvas.className = 'layer-fg';
            canvas.width = 1920;
            canvas.height = 1080;
            layerEl.appendChild(canvas);
            const fgConfig = {
                ...loadedFg.config,
                ...effectRuntimeConfig,
                preloadedImages: prepared.preloadedImages || new Map(),
                layerPlacement: 'foreground'
            };
            if (!fgConfig.imgSrc && layer.src) fgConfig.imgSrc = layer.src;
            const context = canvas.getContext('2d');
            let signalFirstPaint;
            const foregroundReady = new Promise(resolve => { signalFirstPaint = resolve; });
            const stopPaintObserver = observeCanvasFirstPaint(context, signalFirstPaint);
            let newCleanup;
            try {
                newCleanup = loadedFg.module.mount(canvas, context, fgConfig);
            } catch (error) {
                stopPaintObserver();
                throw error;
            }
            foregroundEffectReadiness.push(waitForEffectReady(foregroundReady).finally(stopPaintObserver));
            const cleanupWithObserver = () => {
                stopPaintObserver();
                if (typeof newCleanup === 'function') newCleanup();
            };
            layerEl._cleanupEffects = [...(layerEl._cleanupEffects || []), cleanupWithObserver];
            mountedEffect = true;
        }

        if (backgroundEffectReady) {
            await waitForEffectReady(backgroundEffectReady);
        } else if (mountedEffect) {
            await waitForVisualPaint();
        }
        await Promise.all(foregroundEffectReadiness);
    }

    function currentLayer() { return state.usingA ? el.layerA : el.layerB; }
    function otherLayer() { return state.usingA ? el.layerB : el.layerA; }

    function finishActiveAdvancedTransition() {
        if (typeof activeAdvancedTransitionFinish !== 'function') return;
        const finish = activeAdvancedTransitionFinish;
        activeAdvancedTransitionFinish = null;
        try { finish(); } catch (e) {}
    }

    async function renderSlideInstant(i) {
        finishActiveAdvancedTransition();
        const requestId = ++advancedTransitionRequestId;
        state.i = i;
        const s = state.slides[i];
        const outgoing = currentLayer();
        const incoming = otherLayer();
        incoming.style.display = 'none';
        await setVisual(s, incoming);
        if (requestId !== advancedTransitionRequestId) return false;
        outgoing.removeAttribute('style');
        incoming.removeAttribute('style');
        outgoing.className = 'slideLayer';
        incoming.className = 'slideLayer';
        el.text.innerHTML = sanitizeHTML(s.textHTML || '');
        const img = incoming.querySelector('img.layer-bg');
        if (img && img.complete && img.naturalWidth) fitPaneToImage(img);
        outgoing.style.display = 'none';
        incoming.style.display = 'block';
        state.usingA = !state.usingA;
        el.scrub.value = String(i + 1);
        el.posLabel.textContent = String(i + 1);
        preloadNext();
        return true;
    }

    function finishTransition(outgoing, incoming, i) {
        incoming.className = 'slideLayer';
        outgoing.className = 'slideLayer';
        outgoing.style.display = 'none';
        incoming.style.display = 'block';
        state.usingA = !state.usingA;
        el.scrub.value = String(i + 1);
        el.posLabel.textContent = String(i + 1);
        preloadNext();
    }

    function runSimpleTransition(outgoing, incoming, i, transitionName = 'fade') {
        if (transitionName === 'none') {
            finishTransition(outgoing, incoming, i);
            return;
        }

        const family = `t-${transitionName || 'fade'}`;
        incoming.classList.add(`${family}-enter`);
        outgoing.classList.add(`${family}-exit`);
        void incoming.offsetWidth;
        requestAnimationFrame(() => {
            incoming.classList.add(`${family}-enter-active`);
            outgoing.classList.add(`${family}-exit-active`);
        });
        const onDone = (e) => {
            if (e.target !== incoming) return;
            incoming.removeEventListener('transitionend', onDone);
            finishTransition(outgoing, incoming, i);
        };
        incoming.addEventListener('transitionend', onDone, { once: true });
        el.scrub.value = String(i + 1);
        el.posLabel.textContent = String(i + 1);
        preloadNext();
    }

    function effectStartDelayMs(advancedTransition, transitionName) {
        if (advancedTransition) {
            return Math.max(0, Number(advancedTransition.config.duration || 1) * 1000);
        }
        if (transitionName === 'none') return 0;
        return transitionName === 'dissolve' ? 1100 : 600;
    }

    async function transitionTo(i) {
        finishActiveAdvancedTransition();
        const requestId = ++advancedTransitionRequestId;
        const s = state.slides[i];
        el.text.innerHTML = sanitizeHTML(s.textHTML || '');
        const outgoing = currentLayer();
        const incoming = otherLayer();
        outgoing.removeAttribute('style');
        incoming.removeAttribute('style');
        outgoing.className = 'slideLayer';
        incoming.className = 'slideLayer';
        outgoing.style.display = 'block';
        incoming.style.display = 'none';
        const advancedTransition = normalizeTransitionConfig(s);
        const transitionName = s.transition || 'fade';
        const visualReady = setVisual(s, incoming, {
            playbackStartDelayMs: effectStartDelayMs(advancedTransition, transitionName)
        });
        try {
            await visualReady;
            if (requestId !== advancedTransitionRequestId) return false;
            outgoing.style.display = 'block';
            incoming.style.display = 'block';
            if (!advancedTransition) {
                runSimpleTransition(outgoing, incoming, i, transitionName);
                return true;
            }
            const module = await loadTransitionModule(advancedTransition.engine);
            if (requestId !== advancedTransitionRequestId) return false;
            if (!module || typeof module.runTransition !== 'function') {
                throw new Error(`Transition engine "${advancedTransition.engine}" does not export runTransition`);
            }
            let completed = false;
            let transitionFinish = null;
            transitionFinish = module.runTransition({
                root: el.visual,
                outgoing,
                incoming,
                config: advancedTransition.config,
                duration: Number(advancedTransition.config.duration || 1),
                onComplete: () => {
                    if (completed) return;
                    completed = true;
                    if (activeAdvancedTransitionFinish === transitionFinish) {
                        activeAdvancedTransitionFinish = null;
                    }
                    if (requestId !== advancedTransitionRequestId) return;
                    finishTransition(outgoing, incoming, i);
                }
            });
            if (!completed && typeof transitionFinish === 'function') {
                activeAdvancedTransitionFinish = transitionFinish;
            }
            el.scrub.value = String(i + 1);
            el.posLabel.textContent = String(i + 1);
            preloadNext();
            return true;
        } catch (e) {
            if (requestId !== advancedTransitionRequestId) return false;
            console.error('Advanced transition failed; falling back to fade.', e);
            outgoing.className = 'slideLayer';
            incoming.className = 'slideLayer';
            outgoing.style.display = 'block';
            incoming.style.display = 'block';
            runSimpleTransition(outgoing, incoming, i, 'fade');
            return true;
        }
    }

    function clearTimer() {
        if (nextTimer) {
            clearTimeout(nextTimer);
            nextTimer = null;
        }
    }

    function scheduleNext(sec) {
        clearTimer();
        if (!state.playing) return;
        nextTimer = setTimeout(nextSlide, Math.max(0, sec * 1000));
    }

    function stopActiveAudio(reset = false) {
        activeAudioElements.forEach(audio => {
            try {
                audio.pause();
                if (reset) {
                    audio.removeAttribute('src');
                    audio.load();
                }
            } catch (e) {}
        });
        activeAudioElements = [];

        try {
            el.speech.pause();
            if (reset) {
                el.speech.removeAttribute('src');
                el.speech.load();
            }
        } catch (e) {}
    }

    function stopGlobalAudio(reset = false) {
        activeGlobalAudioElements.forEach(audio => {
            try {
                audio.pause();
                if (reset) {
                    audio.removeAttribute('src');
                    audio.load();
                }
            } catch (e) {}
        });
        if (reset) activeGlobalAudioElements.clear();
    }

    function isGlobalAudioActiveOnSlide(layer, slideIndex) {
        if (!layer || !layer.src) return false;
        if (layer.allSlides !== false) return true;
        const slideNumber = slideIndex + 1;
        const start = Math.max(1, Number(layer.startSlide || 1));
        const end = layer.endSlide ? Math.max(start, Number(layer.endSlide)) : state.slides.length;
        return slideNumber >= start && slideNumber <= end;
    }

    function syncGlobalAudioForCurrentSlide() {
        const layers = state.globalAudioLayers || [];
        const wanted = new Set();

        layers.forEach((layer, index) => {
            if (!isGlobalAudioActiveOnSlide(layer, state.i)) return;
            const key = String(index);
            wanted.add(key);
            if (activeGlobalAudioElements.has(key)) {
                const existing = activeGlobalAudioElements.get(key);
                try {
                    existing.volume = Math.max(0, Math.min(1, Number(layer.volume ?? 1)));
                    if (existing.paused && state.playing) existing.play().catch(() => {});
                } catch (e) {}
                return;
            }

            const audio = new Audio();
            audio.src = layer.src;
            audio.volume = Math.max(0, Math.min(1, Number(layer.volume ?? 1)));
            audio.loop = layer.loop !== false;
            activeGlobalAudioElements.set(key, audio);
            audio.play().catch(() => {});
        });

        activeGlobalAudioElements.forEach((audio, key) => {
            if (wanted.has(key)) return;
            try {
                audio.pause();
                audio.removeAttribute('src');
                audio.load();
            } catch (e) {}
            activeGlobalAudioElements.delete(key);
        });
    }

    function startTimingForCurrent() {
        clearTimer();
        const s = state.slides[state.i];
        stopActiveAudio(true);
        syncGlobalAudioForCurrentSlide();

        const audioLayers = s.audioLayers || [];
        if (audioLayers.length) {
            audioLayers.forEach((layer, index) => {
                if (!layer || !layer.src) return;
                const audio = index === 0 ? el.speech : new Audio();
                audio.src = layer.src;
                audio.currentTime = 0;
                audio.volume = Math.max(0, Math.min(1, Number(layer.volume ?? 1)));
                activeAudioElements.push(audio);
                audio.play().catch(() => {
                    if (index === 0) scheduleNext(s.seconds || 5);
                });
                if (index === 0) {
                    audio.onloadedmetadata = () => {
                        if (isFinite(audio.duration)) scheduleNext(audio.duration + PAD_AFTER_SPEECH);
                    };
                }
            });
        } else {
            scheduleNext((s.seconds != null) ? s.seconds : 5);
        }
    }

    async function playFrom(i, first = false) {
        state.playing = true;
        el.playPause.textContent = 'Pause';
        state.i = i;
        const rendered = first
            ? await renderSlideInstant(i)
            : await transitionTo(i);
        if (rendered && state.playing && state.i === i) startTimingForCurrent();
    }

    function pause() {
        state.playing = false;
        el.playPause.textContent = 'Resume';
        stopActiveAudio(false);
        stopGlobalAudio(false);
        clearTimer();
    }

    function onSpeechEnded() { if (state.playing) scheduleNext(PAD_AFTER_SPEECH); }
    function onSpeechError() { scheduleNext(state.slides[state.i].seconds || 5); }

    function nextSlide() {
        if (!state.playing) return;
        if (state.i >= state.slides.length - 1) {
            state.playing = false;
            el.playPause.textContent = 'Replay';
            stopActiveAudio(false);
            stopGlobalAudio(true);
            return;
        }
        playFrom(state.i + 1);
    }

    function jumpTo(i, auto = true) {
        i = Math.max(0, Math.min(state.slides.length - 1, i));
        state.i = i;
        stopActiveAudio(false);
        stopGlobalAudio(true);
        state.playing = auto;
        el.playPause.textContent = auto ? 'Pause' : 'Start';
        if (auto) {
            playFrom(i);
        } else {
            renderSlideInstant(i);
        }
    }

    function goRel(d) {
        const t = Math.max(0, Math.min(state.slides.length - 1, state.i + d));
        if (t === state.i) return;
        stopActiveAudio(true);
        jumpTo(t, false);
    }

    async function preloadEffectAssets(spec) {
        const key = effectSpecKey(spec);
        if (!key) return;
        if (preloadCache.has(key)) return preloadCache.get(key);

        const promise = (async () => {
            try {
                const assets = await getEffectAssets(spec);
                await Promise.all([
                    ...assets.images.map(loadImagePromise),
                    ...assets.audio.map(loadAudioPromise),
                    loadEffectModule(spec)
                ]);
            } catch (e) {}
        })();
        preloadCache.set(key, promise);
        return promise;
    }

    async function preloadSlide(slideIndex) {
        const s = state.slides[slideIndex];
        if (!s) return;

        const promises = [];
        if (s.background?.src) promises.push(loadImagePromise(s.background.src));
        if (s.background?.effect) promises.push(preloadEffectAssets(s.background.effect));

        (s.foregroundLayers || []).forEach(layer => {
            if (layer.src) promises.push(loadImagePromise(layer.src));
            if (layer.effect) promises.push(preloadEffectAssets(layer.effect));
        });
        (s.audioLayers || []).forEach(layer => {
            if (layer.src) promises.push(loadAudioPromise(layer.src));
        });
        (state.globalAudioLayers || []).forEach(layer => {
            if (isGlobalAudioActiveOnSlide(layer, slideIndex)) promises.push(loadAudioPromise(layer.src));
        });

        const advancedTransition = normalizeTransitionConfig(s);
        if (advancedTransition) {
            const assets = collectEffectAssetUrls(advancedTransition.config);
            promises.push(...[...assets.images].map(loadImagePromise));
            promises.push(...[...assets.audio].map(loadAudioPromise));
            promises.push(loadTransitionModule(advancedTransition.engine).catch(() => null));
        }

        await Promise.all(promises);
    }

    function preloadNext() {
        const promises = [];
        for (let off = 1; off <= PRELOAD_AHEAD_SLIDES; off++) {
            const j = state.i + off;
            if (j >= state.slides.length) break;
            promises.push(preloadSlide(j));
        }
        Promise.all(promises).catch(() => {});
    }

    async function preloadInitialBatch(startIndex) {
        const promises = [preloadSlide(startIndex)];
        for (let off = 1; off <= PRELOAD_AHEAD_SLIDES; off++) {
            const slideIndex = startIndex + off;
            if (slideIndex >= state.slides.length) break;
            promises.push(preloadSlide(slideIndex));
        }
        await Promise.all(promises);
    }

    function refitCurrentPane() {
        const curLayer = state.usingA ? el.layerA : el.layerB;
        const img = curLayer ? curLayer.querySelector('img') : null;
        if (img && img.complete && img.naturalWidth) fitPaneToImage(img);
        if (el.introScreen.style.display !== 'none' && el.opener.complete) fitPaneToImage(el.opener);
    }

    function syncFullscreenUi() {
        const inFullscreen = !!document.fullscreenElement;
        document.body.classList.toggle('is-fullscreen', inFullscreen);
        if (el.fullscreen) el.fullscreen.textContent = inFullscreen ? 'Exit Fullscreen' : 'Fullscreen';
        if (el.exitFullscreen) el.exitFullscreen.hidden = !inFullscreen;
        requestAnimationFrame(refitCurrentPane);
    }

    async function toggleFullscreen() {
        try {
            if (document.fullscreenElement) {
                await document.exitFullscreen();
                return;
            }
            const target = document.documentElement;
            if (target && target.requestFullscreen) await target.requestFullscreen();
        } catch (e) {
            console.error('Could not toggle fullscreen', e);
        }
    }

    function goBack() {
        if (bootstrap.desktopMode && window.movementDesktop) {
            window.movementDesktop.closeCurrentWindow();
            return;
        }
        if (window.history.length > 1) {
            window.history.back();
            return;
        }
        window.location.href = '/';
    }

    async function loadFlowData() {
        if (FLOW_DATA) return FLOW_DATA;
        if (!FLOW_URL) throw new Error('Missing player flow data');
        const res = await fetch(FLOW_URL, { cache: 'no-store' });
        return res.json();
    }

    function normalizeV2Effect(effect) {
        return effect || null;
    }

    function normalizeV2Slide(s) {
        const background = (s && typeof s.background === 'object' && !Array.isArray(s.background))
            ? s.background
            : {};

        const foregroundLayers = Array.isArray(s?.foregroundLayers)
            ? s.foregroundLayers
            : [];

        const audioLayers = Array.isArray(s?.audioLayers)
            ? s.audioLayers
            : [];

        return {
            textHTML: s?.text || '',
            seconds: (s?.seconds != null) ? Number(s.seconds) : null,
            transition: s?.transition || 'fade',
            transitionDraft: (s?.transitionDraft && typeof s.transitionDraft === 'object') ? { ...s.transitionDraft } : null,
            background: {
                src: background.src ? resolveAssetPath(background.src) : null,
                effect: normalizeV2Effect(background.effect)
            },
            foregroundLayers: foregroundLayers.map(layer => ({
                name: layer?.name || '',
                src: layer?.src ? resolveAssetPath(layer.src) : null,
                effect: normalizeV2Effect(layer?.effect)
            })),
            audioLayers: audioLayers.map(layer => ({
                name: layer?.name || '',
                src: layer?.src ? addSessionMediaVersion(resolveAssetPath(layer.src)) : null,
                volume: Number(layer?.volume ?? 1)
            })).filter(layer => layer.src)
        };
    }

    function normalizeGlobalAudioLayer(layer) {
        return {
            name: layer?.name || '',
            src: layer?.src ? resolveAssetPath(layer.src) : null,
            volume: Number(layer?.volume ?? 1),
            allSlides: layer?.allSlides !== false,
            startSlide: layer?.startSlide ? Number(layer.startSlide) : 1,
            endSlide: layer?.endSlide ? Number(layer.endSlide) : null,
            loop: layer?.loop !== false
        };
    }

    function wireControls() {
        if (IS_EDITOR_PREVIEW && el.back) {
            el.back.hidden = true;
        }
        el.startBtn.addEventListener('click', () => {
            state.userInteracted = true;
            if (el.controlsBar) el.controlsBar.style.display = 'flex';
            el.introScreen.classList.add('vanish');
            el.introScreen.addEventListener('transitionend', () => {
                el.introScreen.style.display = 'none';
            }, { once: true });
            playFrom(state.i, true);
        });
        el.ccBtn.addEventListener('click', () => {
            const isHidden = el.captions.classList.toggle('cc-hidden');
            el.ccBtn.style.background = isHidden ? '#fff' : '#e0f2fe';
            el.ccBtn.style.color = isHidden ? '#0f172a' : '#0284c7';
        });
        el.playPause.addEventListener('click', () => state.playing ? pause() : playFrom(state.i, true));
        el.prev.addEventListener('click', () => goRel(-1));
        el.next.addEventListener('click', () => goRel(1));
        if (el.back && !IS_EDITOR_PREVIEW) el.back.addEventListener('click', goBack);
        if (el.fullscreen) el.fullscreen.addEventListener('click', toggleFullscreen);
        if (el.exitFullscreen) el.exitFullscreen.addEventListener('click', toggleFullscreen);
        el.scrub.addEventListener('input', () => {
            const target = Number(el.scrub.value) - 1;
            stopActiveAudio(true);
            jumpTo(target, false);
        });
        el.speech.addEventListener('ended', onSpeechEnded);
        el.speech.addEventListener('error', onSpeechError);
        document.addEventListener('fullscreenchange', syncFullscreenUi);
    }

    async function init() {
        try {
            const data = await loadFlowData();
            if ((data.schemaVersion || 0) !== 2) {
                throw new Error('This player expects schemaVersion 2 flow.json. Please run the v2 converter.');
            }

            state.data = data;
            el.title.textContent = data.title || 'Timeline';
            state.globalAudioLayers = Array.isArray(data.globalAudioLayers)
                ? data.globalAudioLayers.map(normalizeGlobalAudioLayer).filter(layer => layer.src)
                : [];
            let openingImageReady = Promise.resolve();
            if (data.openingImage) {
                const openingImageUrl = resolveAssetPath(data.openingImage);
                el.introScreen.style.display = 'block';
                openingImageReady = new Promise(resolve => {
                    const done = () => {
                        fitPaneToImage(el.opener);
                        resolve();
                    };
                    el.opener.addEventListener('load', done, { once: true });
                    el.opener.addEventListener('error', resolve, { once: true });
                    el.opener.src = openingImageUrl;
                    if (el.opener.complete) done();
                });
            } else {
                el.introScreen.style.display = 'none';
            }

            state.slides = (data.slides || []).map(normalizeV2Slide);

            if (state.slides.length === 0) {
                state.slides = [{
                    textHTML: '[Empty timeline]',
                    seconds: 5,
                    background: { src: null, effect: null },
                    foregroundLayers: [],
                    audioLayers: []
                }];
            }

            const startSlideIndex = parseInt(qs('startSlide') || '0', 10) || 0;
            state.i = Math.max(0, Math.min(startSlideIndex, state.slides.length - 1));

            const originalText = el.startBtn.textContent;
            el.startBtn.textContent = 'Loading...';
            el.startBtn.disabled = true;
            el.startBtn.style.opacity = '0.6';
            el.startBtn.style.cursor = 'wait';
            await Promise.all([openingImageReady, preloadInitialBatch(state.i)]);
            el.startBtn.textContent = originalText;
            el.startBtn.disabled = false;
            el.startBtn.style.opacity = '1';
            el.startBtn.style.cursor = 'pointer';

            el.scrub.max = String(state.slides.length);
            el.maxLabel.textContent = String(state.slides.length);
            el.posLabel.textContent = String(state.i + 1);
            await renderSlideInstant(state.i);
            wireControls();
            syncFullscreenUi();
            if (IS_EDITOR_PREVIEW && window.parent && window.parent !== window) {
                window.parent.postMessage({ type: 'movement-editor-preview-ready' }, '*');
            }
            if (bootstrap.desktopMode && window.movementDesktop) {
                window.movementDesktop.reportReady({
                    surface: 'player',
                    workspaceCount: 0,
                    projectCount: 1
                });
            }
            if (qs('autoPlay') === '1') el.startBtn.click();
        } catch (e) {
            el.title.textContent = 'Error loading slideshow';
            el.status.textContent = e && e.message ? e.message : String(e);
            console.error(e);
        }
    }

    window.addEventListener('resize', () => {
        if (window.timelinePlayer) window.timelinePlayer.refit();
    });
    window.timelinePlayer = { refit: () => refitCurrentPane() };
    init();
})();
